# Generated by Django 3.2.13 on 2022-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_alter_formations_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
