# Generated by Django 4.0.4 on 2022-05-29 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_formations_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='formations',
            name='image',
            field=models.FileField(default='images/default.png', upload_to='images/'),
        ),
    ]
